// Writes lib/firebase_options.dart from a google-services.json file.
// Used by the GitHub workflow:  node tool/gen_firebase_options.mjs <google-services.json> <android package>
import { readFileSync, writeFileSync } from "node:fs";

const [file, pkg] = process.argv.slice(2);
const json = JSON.parse(readFileSync(file, "utf8"));
const client = json.client.find((c) => c.client_info?.android_client_info?.package_name === pkg);
if (!client) {
  console.error(`No Android app with package ${pkg} in ${file}`);
  process.exit(1);
}
const webClient = (client.oauth_client ?? []).find((o) => o.client_type === 3)?.client_id
  ?? (client.services?.appinvite_service?.other_platform_oauth_client ?? [])
    .find((o) => o.client_type === 3)?.client_id
  ?? null;
const q = (s) => `'${String(s).replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;

const dart = `// GENERATED by tool/gen_firebase_options.mjs during the GitHub build. Do not edit.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform != TargetPlatform.android) {
      throw UnsupportedError('This build only has Android settings.');
    }
    return const FirebaseOptions(
      apiKey: ${q(client.api_key[0].current_key)},
      appId: ${q(client.client_info.mobilesdk_app_id)},
      messagingSenderId: ${q(json.project_info.project_number)},
      projectId: ${q(json.project_info.project_id)},
      storageBucket: ${json.project_info.storage_bucket ? q(json.project_info.storage_bucket) : "null"},
    );
  }
}

/// Google sign-in "web client" id (null until Google sign-in is turned on).
// ignore: unnecessary_nullable_for_final_variable_declarations
const String? googleWebClientId = ${webClient ? q(webClient) : "null"};
`;
writeFileSync("lib/firebase_options.dart", dart);
console.log(`Wrote lib/firebase_options.dart for ${json.project_info.project_id}` +
  (webClient ? " (Google sign-in ready)" : " (Google sign-in not turned on yet)"));
